trigger:
  branches:
    include:
      - main

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)_$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  - group: DevOpsTools
  - name: pat
    value: '$(PAT-IvoFulco)'

stages:
  - stage: 'Syncing'
    jobs:
      - job: Validate
        displayName: Azure Wiki sync Azure Repos
        steps:
          - checkout: git://github.com/MicrosoftDocs/azure-devops-docs.git
            clean: true
            persistCredentials: true
            displayName: Clone GitHub repository
